jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    #acl:
    #    connection: default
        
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_USER_TABLERO, ROLE_USER_CUBOS]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]        
        SONATA:
            #- ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented

    providers:
        chain_provider:
             chain: 
                 providers: [fos_userbundle, fr3d_ldapbundle]
        fos_userbundle:
            id: fos_user.user_manager
        fr3d_ldapbundle:
             id: fr3d_ldap.security.user.provider

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        AcmeBundle\Acme\User\LdapUser: plaintext


# La configuracion actual busca al usuario en la base local, luego en LDAP
# y crea el usuario si es necesario, pero con permisos minimos
    firewalls:
        # -> custom firewall for the admin area of the URL
        admin:
            switch_user:        true
            context:            user
            pattern:            /admin(.*)
            fr3d_ldap:           ~
            form_login:
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                default_target_path: /admin/dashboard
                use_referer:    true   
            logout:
                path:           /admin/logout
                target:         /admin/login

            anonymous:    true
        # -> end custom configuration

        # default login area for standard users
        main:
            switch_user:        true
            context:            user
            pattern:            .*
            fr3d_ldap:           ~
            form_login:
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
                default_target_path: /admin/dashboard
                use_referer:    true
            logout:             true
            anonymous:          true

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # -> custom access control for the admin area of the URL
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # -> end

        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        #Especifico para la aplicaci√≥n
        - { path: ^/admin, role: [ROLE_USER, ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/admin/dashboard, role: [ROLE_USER, ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: ROLE_USER }                
