book:
    title:            "Manual TÃ©cnico"
    author:           "eTAB"
    edition:          "First edition"
    language:         es
    publication_date: ~

    generator: { name: easybook, version: 5.0-DEV }

    contents:
        # available content types: acknowledgement, afterword, appendix, author,
        # chapter, conclusion, cover, dedication, edition, epilogue, foreword,
        # glossary, introduction, license, lof (list of figures), lot (list of
        # tables), part, preface, prologue, title, toc (table of contents)
        - { element: cover }
        - { element: toc   }
        - { element: introduction, content: introduccion.md }
        - { element: chapter, number: 1, content: tecnologias.md }
        - { element: chapter, number: 2, content: instalacion.md }
        - { element: chapter, number: 3, content: ModeloDatos.md }
        - { element: chapter, number: 4, content: Gestion_OLAP.md }
        - { element: lof}

    editions:
        ebook:
            format:         epub
            highlight_code: true
            include_styles: true
            labels:         ['appendix', 'chapter']  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       1
                elements:   ["appendix", "chapter", "part"]

        print:
            format:         pdf
            highlight_code: true
            include_styles: true
            isbn:           ~
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            margin:
                top:        25mm
                bottom:     25mm
                inner:      30mm
                outter:     20mm
            page_size:      A4
            theme:          clean
            toc:
                deep:       2
                elements:   ["appendix", "chapter", "part"]
            two_sided:      true

        web:
            format:         html
            highlight_code: true
            include_styles: true
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       2
                elements:   ["appendix", "chapter"]

        website:
            extends:        web
            format:         html_chunked
